### ISSUE TITLE
Uploading content to static

### ISSUE THREAD

**Issue by jasonstrange** [b0tchsec/static.b0tchsec.com#3]
What method do we want to use for uploading the binary content to the static server? SCP? a simple web form behind http auth? FTP?

**Comment by ajacques** [comment]
What are some example user stories that drive this feature request? Should we include this as part of our OP1 planning?

**Comment by jvstrange** [comment]
# User Story:
1. I'm writing up details of a challenge
2. I'm about to link to the binary so others can follow along
3. From here the path can diverge:
    1. I upload the binary to the git repo and link to it from there
        * Easy, quick, but not a good idea.
    2. I upload the  binary to static.b0tchsec.com and link to it from there
        * Currently unknown method to push content to host, but a better idea than storing binaries in git.

**Comment by jasonstrange** [comment]
I propose the following:

Users must have an ssh account on srv1. Each member of b0tchsec will be put in the b0tchsec group and be given write access to /home/b0tchsec/. SCP is your friend.

**Comment by jasonstrange** [comment]
Authors may now sftp://user@static.b0tchsec.com and follow the symlink in their home directory to the b0tchsec directory. Each of us should have rw access to all of /home/b0tchsec. I'm unsure how it'll work when I put a file there, will you have w access to overwrite or delete that file? Needs testing.

**Comment by jasonstrange** [comment]
Unfortunately when one of us would put a file in /home/b0tchsec, it would list us as the owner and then the others wouldn't be able to modify those files from scp/sftp. Created proper user for b0tchsec and added authorized_keys for jstrange & ajacques. Method to upload content to static appears to be finished.
